export const productData = [
    // 임시 데이터입니다.
    {
        id: 1,
        postTitle: '아이엠 그라운드',
        postContent: '자기소개 하기',
        thumbnail: '',
        category: '자유',
        date: '2022. 11. 09.',
        writer: 'IamIM',
        likeCount: 24,
        commentCount: 6,
    },
    {
        id: 2,
        postTitle: '짝짝',
        postContent: '나는 경현',
        thumbnail: '',
        category: '학습',
        date: '2022. 11. 09.',
        writer: '카페인중독',
        likeCount: 11,
        commentCount: 5,
    },
    {
        id: 3,
        postTitle: '짝짝',
        postContent: '나는 민제',
        thumbnail: '',
        category: '일상',
        date: '2022. 11. 10.',
        writer: '처리짱',
        likeCount: 23,
        commentCount: 2,
    },
    {
        id: 4,
        postTitle: '..짝짝',
        postContent: '나는 쑤정',
        thumbnail: '',
        category: '학습',
        date: '2022. 11. 10.',
        writer: '멋쟁이토마토',
        likeCount: 19,
        commentCount: 7,
    },
    {
        id: 5,
        postTitle: '박자는생명',
        postContent: '아 수정이 누나 뭐하는데~~',
        thumbnail: '',
        category: '취업',
        date: '2022. 11. 10.',
        writer: 'MSG',
        likeCount: 19,
        commentCount: 7,
    },
    {
        id: 6,
        postTitle: '마시면서배우는',
        postContent: '재미난 게임',
        thumbnail: '',
        category: '연애',
        date: '2022. 11. 10.',
        writer: '작지만강한우리',
        likeCount: 52,
        commentCount: 46,
    },
];
